# 1.1 Openturns : Point, Sample



## Résumé

Dans cette page, nous présentons les classes `Point` et `Sample`, deux classes de base dans OpenTURNS. Nous présentons les concepts implémentés par ces classes, ainsi que la manière de créer et utiliser de tels objets. Nous montrons comment extraire une ligne ou une colonne avec l'opérateur de slicing. Nous montrons les interactions avec les types Python ainsi qu'avec le module Numpy.

## Références

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Point.html

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Sample.html

## Introduction

Deux types de données incontournables avec OpenTURNS sont :
* `Point` : un point de dimension D ($\in \mathbb{R}^D$) ;
* `Sample` : un échantillon de N points de dimension D.

Objectifs de cette séquence :
* extraire et insérer des valeurs,
* interactions avec l’environnement Python.

In [2]:
!pip install openturns
import openturns as ot

## Point

Nous allons voir comment 
* créer un point de $\mathbb{R}^3$, 
* accéder à ses composantes,
* modifier ses composantes.

Les points sont remplis par des zéros par défaut. 

In [3]:
p = ot.Point(3)
p

class=Point name=Unnamed dimension=3 values=[0,0,0]

Accéder à la seconde composante (d'indice 1).

Note : La numérotation des composantes commence à 0 en Python.

In [4]:
p[1]

0.0

Modifier la seconde composante.

In [5]:
p[1] = 2
p

class=Point name=Unnamed dimension=3 values=[0,2,0]

In [6]:
p.getDimension ()

3

## Sample

Il s’agit d’un échantillon de N points de $\mathbb{R}^D$.
* D est la dimension de l’échantillon.
* N est sa taille (en anglais "*size*").

Un `Sample` peut donc être vu comme une matrice (à N lignes et D colonnes plutôt que D lignes et N colonnes en général par les statisticiens).

*Remarque.* Il existe aussi un objet `ProcessSample` (échantillon de champs, typiquement des fonctions de l’espace ou du temps).

Créer et manipuler un Sample (N=5, D=3).

In [7]:
data = ot.Sample(5, 3)
data

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=3 data=[[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]

In [8]:
data.getSize()

5

In [9]:
data.getDimension()

3

Modifier un Sample.

In [10]:
data [3, 2] = 32
data

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=3 data=[[0,0,0],[0,0,0],[0,0,0],[0,0,32],[0,0,0]]

## Sample : extraire une ligne ou une colonne

* Comme avec les tableaux Numpy, extraire une ligne ou une colonne : opérateur de slicing `:`.
* En Python, le *slicing* est l’acte d’extraire une partie d’un tableau en une seule instruction.
* Objectif : éviter les boucles `for` par vectorisation pour améliorer la performance et la lisibilité

In [11]:
ligne = data [3, :]
ligne

class=Point name=Unnamed dimension=3 values=[0,0,32]

In [12]:
type(ligne)

openturns.typ.Point

In [13]:
colonne = data [:, 2]
colonne

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=1 description=[v2] data=[[0],[0],[0],[32],[0]]

In [14]:
type(colonne)

openturns.typ.Sample

On observe que 
* la `ligne` est de type `Point`
* la `colonne` est de type `Sample`

C'est cohérent : dans un `Sample` en dimension D, une ligne est bien un `Point` en dimension D.

Extraire plusieurs colonnes dans un nouveau `Sample`.

In [15]:
data.getMarginal([0, 2])

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=2 data=[[0,0],[0,0],[0,0],[0,32],[0,0]]

## Créer des Points ou Samples à partir d’une liste Python

Créer un `Point` à partir d’une liste

In [16]:
p1 = ot.Point([2, 3])
p1

class=Point name=Unnamed dimension=2 values=[2,3]

In [17]:
p2 = ot.Point(range(2))
p2

class=Point name=Unnamed dimension=2 values=[0,1]

Un *Pythonisme* utile : la *list comprehension*. Elle permet de créer une liste en réalisant une boucle `for`. Cette construction est souvent utilisée dans la documentation d'OpenTURNS, dans le but d'obtenir des exemples concis.

In [18]:
p3 = ot.Point([i*i for i in p1 ])
p3

class=Point name=Unnamed dimension=2 values=[4,9]

Un *Pythonisme* utile : la répétition avec l'opérateur `*`.

In [19]:
p4 = [5] * 3
p4

[5, 5, 5]

Créer un `Sample` à partir d’une liste de `Point`s.

In [20]:
data = ot.Sample([p1, p2, p3 ])
data

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=3 dimension=2 data=[[2,3],[0,1],[4,9]]

Créer un `Sample` à partir d'un `Point`, répété trois fois.

In [21]:
data = ot.Sample([p4] * 3)
data

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=3 dimension=3 data=[[5,5,5],[5,5,5],[5,5,5]]

Créer un `Sample` à partir d’une liste (imbriquée).

In [22]:
data = ot.Sample([[0, 1], [2, 3], [4, 5]])
data

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=3 dimension=2 data=[[0,1],[2,3],[4,5]]

## Interactions avec Numpy

* Les classes Python extérieures à OpenTURNS ne connaissent pas les classes OpenTURNS. 
* C'est pourquoi il est utile de savoir convertir vers des types Python plus classiques, en particulier les tableaux (arrays) de Numpy.

Créer un `Sample`, puis le convertir en `array` Numpy 2D.

In [25]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 16.0 MB/s eta 0:00:0000:0100:01


In [26]:
X = ot.Sample(5, 3)
import numpy as np
Xarray = np.array(X)
Xarray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
type(Xarray)

numpy.ndarray

Dans l’autre sens : créer un `array` Numpy, puis le convertir en `Sample`.

In [27]:
Xarray = 3.14 * np.ones((5, 3))
X = ot.Sample(Xarray )
X

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=3 data=[[3.14,3.14,3.14],[3.14,3.14,3.14],[3.14,3.14,3.14],[3.14,3.14,3.14],[3.14,3.14,3.14]]

In [28]:
X.getSize()

5

In [29]:
X.getDimension()

3

Créer un `Sample` à partir de 5 valeurs est ambigüe. En effet, est-ce :
* un échantillon de taille 5 en dimension 1 ou
* un échantillon de taille 1 en dimension 5 ?

Pour retirer l'ambiguïté, on utilise le second argument du constructeur de `Sample`, qui permet de spécifier la dimension.

In [32]:
u = np.linspace(0, 1, 5)
u

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Choix A : on créée un `Sample` de taille 5 en dimension 1.

In [33]:
X = ot.Sample(1,u)
X

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=1 dimension=5 data=[[0,0.25,0.5,0.75,1]]

Choix B : on créée un `Sample` de taille 5 en dimension 5.

In [34]:
X= ot.Sample(5,u)
X

class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=5 dimension=5 data=[[0,0.25,0.5,0.75,1],[0,0.25,0.5,0.75,1],[0,0.25,0.5,0.75,1],[0,0.25,0.5,0.75,1],[0,0.25,0.5,0.75,1]]

In [37]:
# Génère une exception attendue
#X = ot.Sample(u)

TypeError: InvalidArgumentException : Invalid array dimension 1 is ambiguous, please set the dimension explicitly

## Point/Sample : exercices

### Exercice 1 : point et norme 1
Créer la variable X contenant un `Point` en dimension 12 contenant les
valeurs numériques suivantes : 0., 1., ..., 11. 
* Utiliser la méthode `norm` pour calculer la norme Euclidienne de X. 
* Comment calculer la norme 1 de X ?

In [50]:
X = ot.Point([float(i) for i in range(12)])
print(X)

print("norm avec ot.norm ",X.norm())

[0,1,2,3,4,5,6,7,8,9,10,11]#12
norm avec ot.norm  22.494443758403985


### Exercice 2 : moyenne et minimum
Créer la variable X contenant un Sample correspondant à l’échantillon
en dimension 2 suivant :
$$
X=
\begin{pmatrix}
0 & 1 \\
2 & 3 \\
4 & 5
\end{pmatrix}
$$
* Utiliser la méthode `computeMean` pour calculer la moyenne empirique.
* Utiliser la méthode `getMin` pour calculer le minimum.



In [62]:
X= ot.Sample(3,2)
X
X2=ot.Sample([[0,1],[2,3],[4,5]])
print(X2)
p1 = ot.Point([0,1])
p2 = ot.Point([2,3])
p3 = ot.Point([4,5])
X3 = ot.Sample([p1,p2,p3])
X3

0 : [ 0 1 ]
1 : [ 2 3 ]
2 : [ 4 5 ]


class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=3 dimension=2 data=[[0,1],[2,3],[4,5]]

In [63]:
print(X3.computeMean())
print(X3.getMin())

[2,3]
[0,1]


### Exercice 3 : différents échantillons

Quel est le résultat des instructions suivantes ?

`
u= np.linspace(0, 1, 10)
ot.Sample(2,u)
ot.Sample(3,u)
ot.Sample(12,u)
`



In [70]:
u = np.linspace(0,1,10)
print(u)

X1 = ot.Sample(2,u)
X1 # 2 fois le vectuer u

X2 = ot.Sample(3,u)
X2 #3 fois u et 12 fois u pour le dernier

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=3 dimension=10 data=[[0,0.111111,0.222222,0.333333,0.444444,0.555556,0.666667,0.777778,0.888889,1],[0,0.111111,0.222222,0.333333,0.444444,0.555556,0.666667,0.777778,0.888889,1],[0,0.111111,0.222222,0.333333,0.444444,0.555556,0.666667,0.777778,0.888889,1]]

### Exercice 4 : un pythonisme

Experimentez le pythonisme suivant, qui permet d’extraire les quatre
champs d’un `Point` en une seule ligne :

`
X= ot.Point([12, 1.680, 3.1416, 2.718])
[ apotres, golden, pi, euler ]=X
`

* Afficher les valeurs de `apotres`, `golden`, `pi` et `euler` et vérifier les valeurs. 
* Que se passe-t-il si on ajoute une dimension dans le `Point` ?



In [78]:
X = ot.Point([12,1.680,3.1416,2.718])
[apotres,golden,pi,euler]=X
print(apotres,golden,pi,euler)
X.add(5)
X
#[apotres,golden,pi,euler]=X erreur


12.0 1.68 3.1416 2.718


ValueError: too many values to unpack (expected 4)

### Exercice 5 : matrice de corrélation

Créer la `CorrelationMatrix` correspondant à la matrice de
corrélation suivante :
$$
A=
\begin{pmatrix}
1   & 0.1 \\
0.1 & 1
\end{pmatrix}
$$
de deux manières différentes : 
* à partir d’une liste Python, 
* à partir  d’un array Numpy.



In [88]:
corM = np.eye(2)
corM[0,1] = 0.1  
corM[1,0] = 0.1

corM

corM_py  = [[1,0.1],[0.1,1]]
corM_py == corM


array([[ True,  True],
       [ True,  True]])


### Exercice 6 : types

Lorsqu'on utilise par exemple la classe `Normal`, les méthodes associées peuvent renvoyer des `Sample`, des `Point` ou des `float` en fonction des cas. Il faut donc être capable de faire cohabiter ces objets. 

* Utiliser l'instruction suivante pour calculer la moyenne d'une variable gaussienne avec les paramètres par défaut :
```
moyenne = ot.Normal().getMean()
```
* Quel est le type de la variable `moyenne` ?
* Extraire la première composante de `moyenne` : quel est son type ?
* Créer un échantillon de 5 réalisations en dimension 3 d'une variable gaussienne centrée-réduite avec l'instruction :
```
X = ot.Normal(3).getSample(5)
```
* Quel est le type de `X` ?

In [94]:
moyenne = ot.Normal().getMean()
type(moyenne) #openturns.typ.Point
type(moyenne[0]) #float
X = ot.Normal(3).getSample(5)
type(X) #openturns.typ.Sample

openturns.typ.Sample

### Exercice 7 : split

La méthode `split` de la classe `Sample` permet de découper un échantillon en deux parties. Par exemple, dans le contexte de la validation d'un méta-modèle, on découpe un échantillon en deux sous-échantillon :
* un sous-échantillon d'apprentissage,
* un sous-échantillon de validation.

L'objectif de cet exercice est de faire des essais avec cette méthode. 
* Créer la variable `data` contenant un échantillon de taille 5 issu d'une loi gaussienne en dimension 2.
* Utiliser la méthode `split` pour créer la variable `reste` contenant un sous-échantillon de taille 2. 
* Observer le contenu de la variable `data`.


In [102]:
data= ot.Normal(2).getSample(5)
data

reste = data.split(2)
print(reste)

print(data)


    [ X0        X1        ]
0 : [ -0.506925 -1.66086  ]
1 : [  2.24623   0.759602 ]
2 : [ -0.510764 -0.633066 ]
    [ X0        X1        ]
0 : [ -0.483642  0.677958 ]
1 : [  1.70938   1.07062  ]
